Witty/Controllers/WittyEntryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Witty.Constants;
using Witty.Mappers;
using Witty.Models;
using Witty.Repositories;
using Witty.ViewModels;

namespace Witty.Controllers
{
    public class WittyEntryController : Controller
    {
        private readonly WittyEntryRepository wittyEntryRepo;

        public WittyEntryController(WittyEntryRepository wittyEntryRepo)
        {
            this.wittyEntryRepo = wittyEntryRepo;
        }

        public IActionResult Index()
        {
            GetWittyEntryFormViewModel viewModel = new GetWittyEntryFormViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Get(GetWittyEntryFormViewModel formViewModel)
        {
            if (formViewModel == null)
                throw new ArgumentNullException();

            if(wittyEntryRepo.Exists(formViewModel.Question))
            {
                WittyEntry wittyEntry = wittyEntryRepo.GetByQuestion(formViewModel.Question);
                WittyEntryViewModel vm = new WittyEntryMapper().Map(wittyEntry);

                return View(vm);
            }

            formViewModel.NotExistsMessage = "Question does not exists";

            return View("Index", formViewModel);

        }

        public IActionResult Add()
        {
            AddWittyEntryFormViewModel viewModel = new AddWittyEntryFormViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Add(AddWittyEntryFormViewModel viewModel)
        {
            if (viewModel == null)
                throw new ArgumentNullException();

            if(ModelState.IsValid)
            {
                WittyEntry we = new WittyEntryMapper().Map(viewModel);

                if(wittyEntryRepo.Exists(we.Question))
                    wittyEntryRepo.AddResponses(we);
                else
                    wittyEntryRepo.Add(we);

                wittyEntryRepo.Save();

                viewModel.AddSuccessMessage = Messenger.AddWittyEntrySuccess;
            }

            return View(viewModel);
        }
    }
}

Witty/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/regular.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/solid.min.css">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tarekraafat-autocomplete.js/10.2.6/css/autoComplete.min.css">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tarekraafat-autocomplete.js/10.2.6/autoComplete.min.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold" href="#">Witty</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page"
                       asp-controller="WittyEntry" asp-action="Index">Home</a>
                    <a class="nav-link" asp-controller="WittyEntry" asp-action="Add">Add</a>
                </div>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>

    <script src="~/js/utilityFunctions.js"></script>
    <script src="~/js/wittyEntryService.js"></script>
    <script src="~/js/filterWittyResponses.js"></script>
    <script src="~/js/getWittyEntryController.js"></script>
    <script src="~/js/autoCompleteService.js"></script>
    <script src="~/js/randomWittyEntryGenerator.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>